export const products = [
  {
    id: 1,
    name: "Lace Balconette Bra",
    description: "Elegant lace balconette bra with underwire support and adjustable straps for a perfect fit.",
    price: 3999,
    image: "/placeholder.svg?height=600&width=600",
    category: "bras",
    featured: true,
    isNew: true,
  },
  {
    id: 2,
    name: "Satin Thong",
    description: "Luxurious satin thong with delicate lace trim for a comfortable and elegant look.",
    price: 1999,
    image: "/placeholder.svg?height=600&width=600",
    category: "panties",
    featured: true,
    isNew: false,
  },
  {
    id: 3,
    name: "Silk Chemise",
    description: "Soft silk chemise with lace details, perfect for a comfortable and elegant night's sleep.",
    price: 7499,
    image: "/placeholder.svg?height=600&width=600",
    category: "sleepwear",
    featured: true,
    isNew: false,
  },
  {
    id: 4,
    name: "Lace Bralette Set",
    description: "Beautiful lace bralette and matching panty set, designed for comfort and style.",
    price: 5999,
    image: "/placeholder.svg?height=600&width=600",
    category: "sets",
    featured: true,
    isNew: true,
  },
  {
    id: 5,
    name: "Push-Up Bra",
    description: "Enhancing push-up bra with smooth cups and comfortable underwire for a natural lift.",
    price: 4499,
    image: "/placeholder.svg?height=600&width=600",
    category: "bras",
    featured: false,
    isNew: false,
  },
  {
    id: 6,
    name: "Lace Boyshort",
    description: "Comfortable lace boyshort with a flattering cut and soft elastic waistband.",
    price: 2499,
    image: "/placeholder.svg?height=600&width=600",
    category: "panties",
    featured: false,
    isNew: false,
  },
  {
    id: 7,
    name: "Satin Pajama Set",
    description: "Luxurious satin pajama set with button-up top and comfortable elastic waist pants.",
    price: 9999,
    image: "/placeholder.svg?height=600&width=600",
    category: "sleepwear",
    featured: false,
    isNew: true,
  },
  {
    id: 8,
    name: "Lace Teddy",
    description: "Stunning lace teddy with adjustable straps and hook-and-eye closure for a perfect fit.",
    price: 6499,
    image: "/placeholder.svg?height=600&width=600",
    category: "sets",
    featured: false,
    isNew: false,
  },
  {
    id: 9,
    name: "Strapless Bra",
    description: "Versatile strapless bra with silicone lining for a secure fit and removable straps.",
    price: 4999,
    image: "/placeholder.svg?height=600&width=600",
    category: "bras",
    featured: false,
    isNew: false,
  },
  {
    id: 10,
    name: "High-Waisted Brief",
    description: "Flattering high-waisted brief with lace details and comfortable coverage.",
    price: 2999,
    image: "/placeholder.svg?height=600&width=600",
    category: "panties",
    featured: false,
    isNew: true,
  },
  {
    id: 11,
    name: "Silk Robe",
    description: "Elegant silk robe with tie waist and side pockets, perfect for lounging in style.",
    price: 12499,
    image: "/placeholder.svg?height=600&width=600",
    category: "sleepwear",
    featured: false,
    isNew: false,
  },
  {
    id: 12,
    name: "Lace Garter Set",
    description: "Complete lace set including bra, panty, and garter belt for a coordinated look.",
    price: 8499,
    image: "/placeholder.svg?height=600&width=600",
    category: "sets",
    featured: false,
    isNew: false,
  },
]

